rabbitmq:
  heartbeat: 600
  blocked_connection_timeout: 300
  host: localhost
  port: 5672
  username: user
  password: "1512"
  input:
    verificationDocument:
      exchange: data-preprocessing-service
      queueName: verification-data
      routingKey: verification-data
    normalizeData:
      exchange: data-preprocessing-service
      queueName: normalization-data
      routingKey: normalization-data
  output:
    verificationResult:
      exchange: user-queries-service
      queueName: verification-result
      routingKey: verification-result

samba:
  host: localhost
  username: victor
  password: "1512"
  shared_directory: NEAT
  netbios_name: NEAT
  workgroup: WORKGROUP

